### ISSUE TITLE
Error: "Uncaught TypeError: Cannot read properties of undefined (reading 'ReactCurrentDispatcher')"

### ISSUE THREAD

**Issue by i-am-rishi** [KarthikAravindR/infinite-canvas#15]
Using version:     "react-infinite-canvas": "^2.1.2"
App: Typescript app
Node Version: 18

Description: I installed this library with command "yarn add react-infinite-canvas" (also tried is using npm command) in my typescript based react app . After doing so I ran the command "yarn run dev" in my app it started throwing error.

![Image](https://github.com/user-attachments/assets/2a21a122-b091-44f2-9a65-8c9e067154e9)

**Comment by KarthikAravindR** [comment]
kindly let me know what version of React are you using? @i-am-rishi

**Comment by KarthikAravindR** [comment]
Fixed the issue @i-am-rishi #18 , kindly check from your side and let me now

**Comment by i-am-rishi** [comment]
Thank You @KarthikAravindR , it worked. Really appreciate your quick response and support. The canvas seems to be working well but I still face few issues don't know whether it's from the library or not. Do you have any latest example for react version 19?

![Image](https://github.com/user-attachments/assets/0bab6eac-5fc4-4ed9-9153-a466def3a0b9)

**Comment by i-am-rishi** [comment]
@KarthikAravindR  Also, please advice me, if I don't want these vertical and horizontal scroll bars to appear then what I'll have to do?

![Image](https://github.com/user-attachments/assets/5a4cda60-a255-47fc-9c25-861f0b39fa27)

**Comment by KarthikAravindR** [comment]
The issue is from library only @i-am-rishi. I will fix it.

Closing this issue. Thank you for using this library 😊
